# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-01 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='applicable_worked_year',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
