# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-01 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_start_date',
            field=models.DateField(null=True),
        ),
    ]
