# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-05 18:41
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from vacations_app.permissions import create_groups_and_apply_permisssions

def add_group_permissions(*args, **kwargs):
    content_type, _ = ContentType.objects.get_or_create(app_label='vacations_app',model='user')

    groups = {
        'staff': [
            ('can_view_other_vacations', 'Can view other vacations', content_type)
        ]
    }

    create_groups_and_apply_permisssions(groups)

class Migration(migrations.Migration):

    dependencies = [
        ('vacations_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions)
    ]
