# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-06 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacations_app', '0003_auto_20191106_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='engineer_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
