# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-08 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations_app', '0004_auto_20191106_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='days_quantity',
            field=models.IntegerField(),
        ),
    ]
