# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-08 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations_app', '0005_auto_20191108_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='from_date',
            field=models.DateField(),
        ),
    ]
