# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-08 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacations_app', '0006_auto_20191108_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedVacations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_year', models.IntegerField()),
                ('total_days', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
