# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-12 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacations_app', '0007_assignedvacations'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
