# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-14 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations_app', '0007_assignedvacations'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_company_id',
            field=models.IntegerField(null=True),
        ),
    ]
